#!/bin/bash
set -e

if [ -e /go/src/github.com/SungardAS/rancher-server-secure-properties/scripts/$1 ]; then
    /go/src/github.com/SungardAS/rancher-server-secure-properties/scripts/"$@"
else
    "$@"
fi
